version: '3.7'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    restart: unless-stopped
    ports:
      - "8041:80"

  database:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:rw

  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  mysqld_exporter:
    image: prom/mysqld-exporter:v0.14.0
    user: root
    ports:
      - 9104:9104
    links:
      - database
    environment:
      - "DATA_SOURCE_NAME=root:root@(database:3306)/demodb"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - database

  redis:
    image: redis:6.2.7

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    volumes:
      - /:/rootfs:ro
      # - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:9.1.8
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-logs:/var/log/grafana

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  prometheus-data:
  db-data:
  grafana-lib:
  grafana-logs:
