version: '3.7'

services:
  nginx:
    image: nginx:1.21
    restart: "no"
    ports:
      - "8041:80"
    volumes:
      - .:/app:delegated # the container’s view is authoritative (permit delays before updates on the container appear in the host)
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile para procesadores ARM
    volumes:
      - .:/app:delegated

  database:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:rw

  prometheus:
    image: prom/prometheus:v2.39.1
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  mysqld_exporter:
    image: prom/mysqld-exporter
    user: root
    ports:
      - 9104:9104
    links:
      - database
    environment:
      - "DATA_SOURCE_NAME=root:root@(database:3306)/demodb"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - database

  redis:
    image: redis:6.2.7

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    volumes:
      - /:/rootfs:ro
      # - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:9.1.8
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-logs:/var/log/grafana
      - ./etc/grafana/provisioning:/etc/grafana/provisioning

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  loki:
    image: "grafana/loki:2.6.1"
    ports:
      - "3100:3100"

  promtail:
    image: "grafana/promtail:2.6.1"
    volumes:
      - ./var/log:/tmp/log/
      - ./etc/promtail/config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

volumes:
  prometheus-data:
  db-data:
  grafana-lib:
  grafana-logs:
